#pragma once

#define ITEM_EKEEKE 0x00
#define ITEM_MAGIC_SWORD 0x01
#define ITEM_ICE_SWORD 0x02
#define ITEM_THUNDER_SWORD 0x03
#define ITEM_GAIA_SWORD 0x04
#define ITEM_FIREPROOF_BOOTS 0x05
#define ITEM_IRON_BOOTS 0x06
#define ITEM_HEALING_BOOTS 0x07
#define ITEM_SPIKE_BOOTS 0x08
#define ITEM_STEEL_BREAST 0x09
#define ITEM_CHROME_BREAST 0x0A
#define ITEM_SHELL_BREAST 0x0B
#define ITEM_HYPER_BREAST 0x0C
#define ITEM_MARS_STONE 0x0D
#define ITEM_MOON_STONE 0x0E
#define ITEM_SATURN_STONE 0x0F
#define ITEM_VENUS_STONE 0x10
// Awakening Book = 0x11
#define ITEM_DETOX_GRASS 0x12
#define ITEM_GAIA_STATUE 0x13
#define ITEM_GOLDEN_STATUE 0x14
#define ITEM_MIND_REPAIR 0x15
#define ITEM_CASINO_TICKET 0x16
#define ITEM_AXE_MAGIC 0x17
#define ITEM_BLUE_RIBBON 0x18
#define ITEM_BUYER_CARD 0x19
#define ITEM_LANTERN 0x1A
#define ITEM_GARLIC 0x1B
#define ITEM_ANTI_PARALYZE 0x1C
#define ITEM_STATUE_JYPTA 0x1D
#define ITEM_SUN_STONE 0x1E
#define ITEM_ARMLET 0x1F
#define ITEM_EINSTEIN_WHISTLE 0x20
// Detox Book 0x21
// AntiCurse 0x22
// Record Book 0x23
#define ITEM_SPELL_BOOK 0x24
// Hotel Register 0x25
// Island Map 0x26
#define ITEM_LITHOGRAPH 0x27
#define ITEM_RED_JEWEL 0x28
#define ITEM_PAWN_TICKET 0x29
#define ITEM_PURPLE_JEWEL 0x2A
#define ITEM_GOLA_EYE 0x2B
#define ITEM_DEATH_STATUE 0x2C
#define ITEM_DAHL 0x2D
#define ITEM_RESTORATION 0x2E
#define ITEM_LOGS 0x2F
#define ITEM_ORACLE_STONE 0x30
#define ITEM_IDOL_STONE 0x31
#define ITEM_KEY 0x32
#define ITEM_SAFETY_PASS 0x33
// No52 0x34
#define ITEM_BELL 0x35
#define ITEM_SHORT_CAKE 0x36
#define ITEM_GOLA_NAIL 0x37
#define ITEM_GOLA_HORN 0x38
#define ITEM_GOLA_FANG 0x39
#define ITEM_5_GOLDS 0x3A
#define ITEM_20_GOLDS 0x3B
#define ITEM_50_GOLDS 0x3C
#define ITEM_200_GOLDS 0x3D
#define ITEM_LIFESTOCK 0x3E
#define ITEM_NONE 0x3F