#pragma once

#include "../tools/flag.h"

constexpr Flag FLAG_NIGEL_AWOKEN_FROM_KNC_WATERFALL (0x00, 7);
constexpr Flag FLAG_INTRO_FINISHED                  (0x00, 5);
constexpr Flag FLAG_KEYDOOR_OPENED_IN_KNC           (0x00, 4);
constexpr Flag FLAG_FARA_KIDNAPPED                  (0x00, 0);

constexpr Flag FLAG_TALKED_WITH_HIDDEN_VILLAGER_RYUMA       (0x02, 7);
constexpr Flag FLAG_SPIED_ON_GUMI_RITUAL                    (0x02, 4);
constexpr Flag FLAG_BRIDGE_TO_GUMI_REPAIRED                 (0x02, 2);
constexpr Flag FLAG_MASSAN_VILLAGER_WARNED_BRIDGE_IS_BROKEN (0x02, 0);

constexpr Flag FLAG_FIRST_ENCOUNTER_WITH_DUKE          (0x03, 7);
constexpr Flag FLAG_SAW_FRIDAY_CUTSCENE_AT_MADAME_YARD (0x03, 6);
constexpr Flag FLAG_ARTHUR_GAVE_ACCESS_TO_CASTLE       (0x03, 5);

constexpr Flag FLAG_TALKED_WITH_MERCATOR_GUARDS_ASKING_GOLDS (0x04, 7);
constexpr Flag FLAG_SAW_KAYLA_RAFT_CUTSCENE_AT_RYUMA         (0x04, 6);
constexpr Flag FLAG_ALLOWED_TO_GO_IN_THIEVES_HIDEOUT         (0x04, 0);

constexpr Flag FLAG_TALKED_WITH_MADAME_YARD_GIRL_HINTING_FORTUNE_TELLER (0x05, 6);
constexpr Flag FLAG_SAW_ARTHUR_AT_CASTLE_BACKDOOR                       (0x05, 5);

constexpr Flag FLAG_ASSISTED_TO_MERCATOR_BANQUET             (0x12, 4);
constexpr Flag FLAG_TALKED_WITH_KITCHEN_WOMAN_BEFORE_BANQUET (0x12, 3);
constexpr Flag FLAG_SERVANT_BORUGHT_US_TO_BEDROOM            (0x12, 2);
constexpr Flag FLAG_DUKE_LEFT_ROOM_AFTER_FIRST_ENCOUNTER     (0x12, 1);

constexpr Flag FLAG_COMPLETED_MERCATOR_JARS_SIDEQUEST_TWO_TIMES (0x13, 6);
constexpr Flag FLAG_SAW_TRAPPED_KAYLA_CUTSCENE_IN_DUNGEON       (0x13, 1);
constexpr Flag FLAG_THREW_IN_DUNGEON_BY_DUKE                    (0x13, 0);

constexpr Flag FLAG_SAW_KAYLA_LITHOGRAPH_CUTSCENE   (0x14, 7);
constexpr Flag FLAG_SLEPT_AT_MERCATOR_AFTER_BANQUET (0x14, 0);

constexpr Flag FLAG_TOOK_PURPLE_JEWEL_IN_MIR_TOWER (0x17, 6);
constexpr Flag FLAG_SAW_MIRO_CLOSE_KEYDOOR         (0x17, 3);

constexpr Flag FLAG_TALKED_WITH_ARTHUR_REVEALING_DUKE_ESCAPE (0x20, 6);         
constexpr Flag FLAG_ZAK_FLEW_OFF_MERCATOR_DUNGEON            (0x20, 5);
constexpr Flag FLAG_SAW_PRINCESS_LARA_IN_MERCATOR_DUNGEON    (0x20, 4);

constexpr Flag FLAG_DEX_KILLED (0x26, 7);

constexpr Flag FLAG_PRISONERS_OPENED_UNFINISHED_TUNNEL (0x27, 5);
constexpr Flag FLAG_OPENED_MERCATOR_TELEPORTER_TO_KNC  (0x27, 1);

constexpr Flag FLAG_SAW_DUKE_MERCATOR_ON_RAFT_NEAR_DESTEL (0x28, 7);
constexpr Flag FLAG_SAW_DEXTER_DIE_IN_CRYPT               (0x28, 6);
constexpr Flag FLAG_SAW_KAYLA_CUTSCENE_IN_GREENMAZE       (0x28, 5);

constexpr Flag FLAG_FRIDAY_TALKED_AFTER_GETTING_LANTERN (0x29, 6);

constexpr Flag FLAG_SAW_ZAK_ON_BRIDGE             (0x2A, 7);
constexpr Flag FLAG_SAW_DUKE_ENTERING_LAKE_SHRINE (0x2A, 0);
 
constexpr Flag FLAG_SAW_DUKE_TAUNTING_IN_SHELL_BREAST_ROOM (0x2B, 7);
constexpr Flag FLAG_SECOND_RAFT_PLACED_IN_KNL              (0x2B, 1);
