#pragma once

#include <cstdint>

constexpr uint8_t ITEM_EKEEKE = 0x00;
constexpr uint8_t ITEM_MAGIC_SWORD = 0x01;
constexpr uint8_t ITEM_ICE_SWORD = 0x02;
constexpr uint8_t ITEM_THUNDER_SWORD = 0x03;
constexpr uint8_t ITEM_GAIA_SWORD = 0x04;
constexpr uint8_t ITEM_FIREPROOF_BOOTS = 0x05;
constexpr uint8_t ITEM_IRON_BOOTS = 0x06;
constexpr uint8_t ITEM_HEALING_BOOTS = 0x07;
constexpr uint8_t ITEM_SPIKE_BOOTS = 0x08;
constexpr uint8_t ITEM_STEEL_BREAST = 0x09;
constexpr uint8_t ITEM_CHROME_BREAST = 0x0A;
constexpr uint8_t ITEM_SHELL_BREAST = 0x0B;
constexpr uint8_t ITEM_HYPER_BREAST = 0x0C;
constexpr uint8_t ITEM_MARS_STONE = 0x0D;
constexpr uint8_t ITEM_MOON_STONE = 0x0E;
constexpr uint8_t ITEM_SATURN_STONE = 0x0F;
constexpr uint8_t ITEM_VENUS_STONE = 0x10;
constexpr uint8_t ITEM_AWAKENING_BOOK = 0x11; // Fake item
constexpr uint8_t ITEM_DETOX_GRASS = 0x12;
constexpr uint8_t ITEM_GAIA_STATUE = 0x13;
constexpr uint8_t ITEM_GOLDEN_STATUE = 0x14;
constexpr uint8_t ITEM_MIND_REPAIR = 0x15;
constexpr uint8_t ITEM_CASINO_TICKET = 0x16;
constexpr uint8_t ITEM_AXE_MAGIC = 0x17;
constexpr uint8_t ITEM_BLUE_RIBBON = 0x18;
constexpr uint8_t ITEM_BUYER_CARD = 0x19;
constexpr uint8_t ITEM_LANTERN = 0x1A;
constexpr uint8_t ITEM_GARLIC = 0x1B;
constexpr uint8_t ITEM_ANTI_PARALYZE = 0x1C;
constexpr uint8_t ITEM_STATUE_JYPTA = 0x1D;
constexpr uint8_t ITEM_SUN_STONE = 0x1E;
constexpr uint8_t ITEM_ARMLET = 0x1F;
constexpr uint8_t ITEM_EINSTEIN_WHISTLE = 0x20;
constexpr uint8_t ITEM_BLUE_JEWEL = 0x21; // Detox Book in base game
constexpr uint8_t ITEM_YELLOW_JEWEL = 0x22; // AntiCurse Book in base game
constexpr uint8_t ITEM_RECORD_BOOK = 0x23;
constexpr uint8_t ITEM_SPELL_BOOK = 0x24;
constexpr uint8_t ITEM_HOTEL_REGISTER = 0x25; // Fake item
constexpr uint8_t ITEM_ISLAND_MAP = 0x26; // Fake item
constexpr uint8_t ITEM_LITHOGRAPH = 0x27;
constexpr uint8_t ITEM_RED_JEWEL = 0x28;
constexpr uint8_t ITEM_PAWN_TICKET = 0x29;
constexpr uint8_t ITEM_PURPLE_JEWEL = 0x2A;
constexpr uint8_t ITEM_GOLA_EYE = 0x2B;
constexpr uint8_t ITEM_DEATH_STATUE = 0x2C;
constexpr uint8_t ITEM_DAHL = 0x2D;
constexpr uint8_t ITEM_RESTORATION = 0x2E;
constexpr uint8_t ITEM_LOGS = 0x2F;
constexpr uint8_t ITEM_ORACLE_STONE = 0x30;
constexpr uint8_t ITEM_IDOL_STONE = 0x31;
constexpr uint8_t ITEM_KEY = 0x32;
constexpr uint8_t ITEM_SAFETY_PASS = 0x33;
constexpr uint8_t ITEM_GREEN_JEWEL = 0x34; // No52 in base game (unused item)
constexpr uint8_t ITEM_BELL = 0x35;
constexpr uint8_t ITEM_SHORT_CAKE = 0x36;
constexpr uint8_t ITEM_GOLA_NAIL = 0x37;
constexpr uint8_t ITEM_GOLA_HORN = 0x38;
constexpr uint8_t ITEM_GOLA_FANG = 0x39;
constexpr uint8_t ITEM_NO_SWORD = 0x3A;
constexpr uint8_t ITEM_NO_ARMOR = 0x3B;
constexpr uint8_t ITEM_NO_BOOTS = 0x3C;
constexpr uint8_t ITEM_NO_RING = 0x3D;
constexpr uint8_t ITEM_LIFESTOCK = 0x3E;
constexpr uint8_t ITEM_NONE = 0x3F;
constexpr uint8_t ITEM_GOLDS_START = 0x40;
