name: Compile

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: update-submodules
      run: git submodule update --recursive
      working-directory: "."
    - name: cmake
      run: cmake -G "Unix Makefiles"
      working-directory: "."
    - name: make
      run: make
      working-directory: "."
